apiVersion: v1
kind: Secret
metadata:
  name: {{ include "expense-tracker.fullname" . }}-secret
  labels:
    {{- include "expense-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  mysql_db_host: {{ .Values.mysql.service_ip | b64enc | quote }}
  mysql_db_username: {{ .Values.mysql.db_username | b64enc | quote }}
  mysql_db_password: {{ .Values.mysql.db_password | b64enc | quote }}
  mysql_db_name: {{ .Values.mysql.db_name | b64enc | quote }}
