apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-backend
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-backend
  template:
    metadata:
      labels:
        app: expense-tracker-backend
    spec:
      containers:
        - name: expense-tracker-backend
          image: pratikrshah/expense_tracker_backend:v1.0
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secret
                  key: mysql_db_host
            - name: MYSQL_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secret
                  key: mysql_db_username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secret
                  key: mysql_db_password
            - name: MYSQL_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: expense-tracker-secret
                  key: mysql_db_name
